// import { connectDB } from "@/lib/db";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import Providers from "./providers";

export const metadata = {
  title: "Gadgets BD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // await connectDB();

  return (
    <html lang="en">
      <body className="bg-amazon-background text-amazon-text flex flex-col min-h-screen">
        <Providers>
          {children}
          <Toaster position="top-right" reverseOrder={false} />
        </Providers>
      </body>
    </html>
  );
}
