// import { connectDB } from "@/lib/db";

import Providers from "../providers";

export const metadata = {
  title: "Gadgets BD",
  description: "Generated by create next app",
};

export default function HomeLayout({ children, authModal }) {
  // await connectDB();

  return (
    <>
      <Providers>
        {children}
        {authModal}
      </Providers>
    </>
  );
}
